---

# Any hosts

- hosts:
    - any
  become: true
  vars_files:
    - variables.yml
    - encrypted_variables.yml
  tasks:
  - name: Place hosts files for internal domain resolving
    template:
      src: templates/etc/hosts
      dest: /etc/hosts

# ELK hosts

- hosts:
    - elk

  become: true

  vars_files:
    - variables.yml
    - encrypted_variables.yml

  handlers:
  - name: restart services
    service:
      name: "{{ item }}"
      state: restarted
    with_items:
      - "{{ elastic_services }}"

  tasks:

# Install Java

  - name: Add Oracle Java Repository
    become: yes
    apt_repository:
      repo: 'ppa:webupd8team/java'

  - name: Accept Java 8 License
    become: yes
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: Install Oracle Java 8
    become: yes
    apt: name={{item}} state=latest
    with_items:
      - "{{ java_packages }}"

# Add Elastic repo

  - name: Add an apt signing key for Elastic packages
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present

  - name: Add an apt repository for Elastic packages
    apt_repository:
      repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
      state: present
      filename: 'elastic-5.x.list'

# Install Elasticsearch & Kibana

  - name: Install Elasticsearch packages
    package:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - "{{ elastic_packages }}"

# Configure Elasticsearch

  - name: Make sure Elasticsearch listen on localhost
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: '^# network.host: 192.168.0.1'
      line: 'network.host: localhost'
      backrefs: yes
    notify: restart services

# Configure Kibana

  - name: Make sure Kibana listen on localhost
    lineinfile:
      path: /etc/kibana/kibana.yml
      regexp: '^#server.host: "localhost"'
      line: 'server.host: "localhost"'
      backrefs: yes
    notify: restart services

# Enable services to start up automatically
    
  - name: Make sure sevices are started upon boot
    service:
      name: "{{ item }}"
      enabled: yes
    with_items:
      - "{{ elastic_services }}"
      
